version: '3.1'

services:
  app:
    build:
      context: ./backend/java-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JDBC_DATABASE_URL=${JDBC_DATABASE_URL}
      - JDBC_USERNAME=${JDBC_USERNAME}
      - JDBC_PASSWORD=${JDBC_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${JDBC_PASSWORD}
      MYSQL_DATABASE: artdb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: